// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function Cmp2(Props) {
  return React.createElement("div", undefined, "Hello from rescript.");
}

Cmp2.displayName = "Cmp2";

var make = Cmp2;

exports.make = make;
/*  Not a pure module */
