// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var TestSvg = require("./TestSvg.bs.js");
var JsonParseView = require("./JsonParseView.bs.js");
var Expln_React_ViewSelector = require("@expln/utils/src/main/Expln_React_ViewSelector.bs.js");

function MainView(Props) {
  return React.createElement(Expln_React_ViewSelector.make, {
              allViews: [
                {
                  id: "1",
                  title: "JsonParseView",
                  render: (function (param) {
                      return React.createElement(JsonParseView.make, {});
                    })
                },
                {
                  id: "2",
                  title: "TestSvg",
                  render: (function (param) {
                      return React.createElement(TestSvg.make, {});
                    })
                }
              ],
              defaultViewId: "2"
            });
}

var make = MainView;

exports.make = make;
/* react Not a pure module */
